src/Entity/Job.php
<?php

namespace App\Entity;

/**
 * This is the main entity for job containing many properties.
 * Some of the properties has been omitted for the sake of this task and are listed in TODO part of README
 * @package App\Entity
 */
class Job
{
    private string $jobId;
    private ?string $publicId;
    private bool $draft;
    private bool $active;
    private string $title;
    private string $description;
    private ?int $closedDuration;
    private string $lastUpdate;
    private string $dateCreated;
    private array $workFields;
    private array $education;
    private array $salary;
    private Employment $employment;
    private Personalist $personalist;
    private Contact $contact;

    public function __construct(
        string $jobId,
        ?string $publicId,
        bool $draft,
        bool $active,
        string $title,
        string $description,
        ?int $closedDuration,
        string $lastUpdate,
        string $dateCreated,
        array $workFields,
        array $education,
        array $salary,
        Employment $employment,
        Personalist $personalist,
        Contact $contact
    ) {
        $this->jobId = $jobId;
        $this->publicId = $publicId;
        $this->draft = $draft;
        $this->active = $active;
        $this->title = $title;
        $this->description = $description;
        $this->closedDuration = $closedDuration;
        $this->lastUpdate = $lastUpdate;
        $this->dateCreated = $dateCreated;
        $this->workFields = $workFields;
        $this->education = $education;
        $this->salary = $salary;
        $this->employment = $employment;
        $this->personalist = $personalist;
        $this->contact = $contact;
    }

    public function getJobId(): string
    {
        return $this->jobId;
    }

    public function getPublicId(): ?string
    {
        return $this->publicId;
    }

    public function isDraft(): bool
    {
        return $this->draft;
    }

    public function isActive(): bool
    {
        return $this->active;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function getDescription(): string
    {
        return $this->description;
    }

    public function getClosedDuration(): ?int
    {
        return $this->closedDuration;
    }

    public function getLastUpdate(): string
    {
        return $this->lastUpdate;
    }

    public function getDateCreated(): string
    {
        return $this->dateCreated;
    }

    public function getWorkFields(): array
    {
        return $this->workFields;
    }

    public function getEducation(): array
    {
        return $this->education;
    }

    public function getSalary(): array
    {
        return $this->salary;
    }

    public function getEmployment(): Employment
    {
        return $this->employment;
    }

    public function getPersonalist(): Personalist
    {
        return $this->personalist;
    }

    public function getContact(): Contact
    {
        return $this->contact;
    }
}

src/Entity/Salary.php
<?php

namespace App\Entity;

/**
 * This class stores data about salary and belongs to a job
 * @package App\Entity
 */
class Salary
{
    private float $min;
    private float $max;
    private string $currency;
    private string $unit;
    private bool $visible;

    public function __construct(
        float $min,
        float $max,
        string $currency,
        string $unit,
        bool $visible
    ) {
        $this->min = $min;
        $this->max = $max;
        $this->currency = $currency;
        $this->unit = $unit;
        $this->visible = $visible;
    }

    public function getMin(): float
    {
        return $this->min;
    }

    public function getMinWithCurrency(): string
    {
        return $this->min . ' ' . $this->currency;
    }

    public function getMax(): float
    {
        return $this->max;
    }

    public function getMaxWithCurrency(): string
    {
        return $this->max . ' ' . $this->currency;
    }

    public function getCurrency(): string
    {
        return $this->currency;
    }

    public function getUnit(): string
    {
        return $this->unit;
    }

    public function isVisible(): bool
    {
        return $this->visible;
    }
}

src/Controller/JobController.php
<?php

namespace App\Controller;

use App\Service\DtoService;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Throwable;

/**
 * main application controller handling requests for each route so far
 */
class JobController extends AbstractController
{
    #[Route('/')]
    public function index(DtoService $dtoService, Request $request, LoggerInterface $logger)
    {
        try {
            $jobData = $dtoService->getJobList($request->get('page', 1));

            return $this->render('job/list.html.twig', [
                'jobs' => $jobData['jobs'],
                'page' => $jobData['page'],
                'totalPages' => $jobData['totalPages'],
            ]);
        } catch (Throwable $t) {
            $logger->error($t->getMessage());

            return new Response('An error ocurred, try again later', 500);
        }
    }
}

templates/job/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="container">
        <table class="table">
            <tr>
                <th>
                    Job ID
                </th>
                <th>
                    Public ID
                </th>
                <th>
                    Draft
                </th>
                <th>
                    Active
                </th>
                <th>
                    Title
                </th>
                <th>
                    Last update
                </th>
                <th>
                    Salary
                </th>
            </tr>
            {% for job in jobs %}
                <tr>
                    <td>
                        {{ job.jobId }}
                    </td>
                    <td>
                        {{ job.publicId }}
                    </td>
                    <td>
                        {{ job.isDraft() ? 'yes' : 'no' }}
                    </td>
                    <td>
                        {{ job.isActive() ? 'yes' : 'no' }}
                    </td>
                    <td>
                        {{ job.title }}
                    </td>
                    <td>
                        {{ job.lastUpdate }}
                    </td>
                    <td>
                        <ul>
                            {% for salary in job.salary %}
                                {% if salary.isVisible() %}
                                    <li>
                                        {{ salary.unit }}
                                        <ul>
                                            {% if salary.min > 0 %}
                                                <li>
                                                    from: {{ salary.minWithCurrency}}
                                                </li>
                                            {% endif %}
                                            {% if salary.max > 0 %}
                                                <li>
                                                    up to: {{ salary.maxWithCurrency }}
                                                </li>
                                            {% endif %}
                                        </ul>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
            {% endfor %}
        </table>
        {% include 'partials/pagination.html.twig' with {
            currentPage: page,
            lastPage: totalPages,
            showAlwaysFirstAndLast: true
        } only %}
    </div>

{% endblock %}